name: deploy-flask-app

on:
  # workflow_run:
  #   workflows: ["build-and-push"] #Name of upstream workflow
  #   types: [completed]
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploye:
    env:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
    runs-on: [self-hosted, Linux]

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: deploy with docker compose
        run: docker compose down && docker compose up -d --build --force-recreate --pull always
